-- Recurring invoice/quote series
create table if not exists recurring_series (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users (id) on delete cascade,
  customer_id uuid not null references customers (id) on delete cascade,
  name text not null default '',
  enabled boolean not null default true,
  document_type text not null default 'invoice',
  frequency text not null default 'monthly',
  day_of_month int not null default 1,
  amount numeric not null default 0,
  title text not null default '',
  notes text not null default '',
  invoice_type text not null default 'final',
  next_run_date date not null default current_date,
  last_run_at timestamptz,
  total_runs int not null default 0,
  max_runs int,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_recurring_series_user_id on recurring_series (user_id);
create index if not exists idx_recurring_series_next_run on recurring_series (next_run_date) where enabled = true;

alter table recurring_series enable row level security;

create policy "recurring_series by owner" on recurring_series
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Track which invoices/quotes were generated by recurring series
alter table invoices add column if not exists recurring_series_id uuid references recurring_series (id) on delete set null;
alter table quotes add column if not exists recurring_series_id uuid references recurring_series (id) on delete set null;
